### ISSUE TITLE
Waveform viewer doesn't work with Gtk+ 3.10

### ISSUE THREAD

**Issue by laspic** [gkarsay/parlatype#1]
Thank you very much for your job. Parlatype is exactly what I need, and it globally works very well. 

But one thing need to be fix : I don't have any waveform and timeline displayed (the first one is optional, the second one is a little bit annoying). 

I'm using the 1.4.1 version, installed from your PPA. I'm also under Ubuntu 14.04, maybe it's the reason of this issue ?

**Comment by gkarsay** [comment]
Thank you for reporting bug #1!  Did you install from the PPA with stable releases or the testing PPA? In version 1.4.1 there is no timeline yet, however, there should be a waveform. The timeline will be introduced in version 1.5 in February 2017 and it's already available in the testing PPA.
Is there any output if you start parlatype from command line?

**Comment by laspic** [comment]
You're welcome, it's my pleasure. :)
I installed from the PPA with stables releases. I will try the testing PPA.
Here are outputs from the terminal (in attached file).
[parlatype_outputs.txt](https://github.com/gkarsay/parlatype/files/732118/parlatype_outputs.txt)

**Comment by laspic** [comment]
OK. You can close the bug, I've found the problem.
I've updated GTK 3.10 to GTK 3.12 (not native under Ubuntu 14.04), and everything works fine now.

**Comment by gkarsay** [comment]
I believe this bug is fixed now and it should work with Gtk+ 3.10, too. Please reopen it, if it still doesn't work.

**Comment by gkarsay** [comment]
Lately I tried with Ubuntu 14.04 and it still didn't work well, even if using Gtk 3.12.
Triaging the problem I found out that the init function of the waveform viewer is not called, unlike on my other systems, starting with Gtk 3.14. I have no clue, why the init function is not called (maybe some GtkBuilder thing) and of course this results in a crash sooner or later.

**Comment by gkarsay** [comment]
I believe this bug is fixed now and it should work with Gtk+ 3.10, too. I tested it with Ubuntu 14.04 (with Unity) in Virtualbox. My previous comment, by the way, is completely wrong.

Commit a8f9a4f363b32bcf27acad814120d76a5b288d90 makes the waveviewer visible in Gtk+ 3.10.
Commit abf2d5e91be7c1c85efe6c02ad0f22cd8cbaba1f chooses an existing color for the waveform (it depended on Adwaita theme before, Unity has something different)
Commit ef7a12475cab674222a529d43257e468772fcf20 fixes a very frequent, important warning I first saw in Gtk+ 3.10 or rather GObject, but it might appear in other versions as well
Commit b226479f1f121aad849073f036f376237140df29 fixes a minor warning that is probably present only in Gtk+ 3.10.
