### ISSUE TITLE
Open does not show any files in flatpak version

### ISSUE THREAD

**Issue by elya5** [gkarsay/parlatype#21]
### Installation and version

How did you install Parlatype?
From flathub (flatpak version 0.10.0)

### Your desktop environment

* What's your distro? Fedora 27
* What's your desktop environment? GNOME

### Issue

* What is not working as expected? If I click the "open" button, the file chooser dialog does not show any files or directories
* Does it happen all the time? Yes
* If you start Parlatype from terminal, is there any error output? There is no output

### Other information
![screenshot of empty filechooser](https://user-images.githubusercontent.com/4464481/32862338-1337b0b2-ca58-11e7-8974-ced114ff3b54.png)

**Comment by gkarsay** [comment]
Thank you for bug report! As it is related to packaging rather than the source code, I'm going to "move" it to https://github.com/flathub/com.github.gkarsay.parlatype/issues/1 and close it here.

**Comment by AlessandroBono** [comment]
Hi! Did you consider to use the [GtkFileChooserNative APIs](https://developer.gnome.org/gtk3/stable/gtk3-GtkFileChooserNative.html) instead of GtkFileChooserDialog? Doing so, you can keep your application sandboxed (e.g.: don't give it access to the home directory) while still being able to open files outside the sandbox.

**Comment by gkarsay** [comment]
Thanks, I didn't know that before. I will consider it for the next release.
