### ISSUE TITLE
[Feature request] More shortcuts

### ISSUE THREAD

**Issue by chrwahl** [gkarsay/parlatype#27]
I just installed Parlatype using the PPA on Ubuntu 17.10. Seams to work really well. I haven't tried the LibreOffice integration yet, but I will.

I have a couple of suggestions for Parlatype:

- More shortcuts for controlling audio, like`space bar` for play/pause and `Ctrl+arrow-left`/`Ctrl+arrow-right` for jumping back and forward. If I transcribe in a text editor and use `Alt+tab` to move to Parlatype I would like to keep my hands on the keyboard and just hit `space bar` to pause/play.
- Maybe even shortcuts that you can customize.
- Customizing the copying format for timestamp with RegEx
- Move the play button alongside the other controls (jumping back and forward) -- or the other way around (if the buttons are needed at all in the UI?).

**Comment by JLuc** [comment]
I just discover parlatype and find it very usefull.
I agree with these new shortcut proposals, and realize that "éspace bar" to "Pause/Play" would be very handy
The short cut i miss the most is some shortcut for "forward" and "backward" action. There are preferences to set the delay value for these action, but they can only be triggered with 2 tiny little buttons that have to be clicked... That is not handy at all.
Please make "forward" and "backward" action available through some keyboard shortcut. Ctrl+arrows could be OK but would that not interfere with text editor ? Maybe Alt+arrows would interfere less.

**Comment by JLuc** [comment]
#18 proposes Shift + space to Play/pause and Shift + Alt + Left Arrow/Right Arrow to go a short while back/forth. That'd be very OK.

**Comment by chrwahl** [comment]
Sounds fine to me

**Comment by gkarsay** [comment]
Thanks for you suggestions, I just added shortcuts for play/pause (ctrl + space), jump back (ctrl + left arrow) and jump forward (ctrl + right arrow). There has to be some modifier key, I chose ctrl, because without modifier those keys are used in GTK+ for keyboard navigation and space is used to click buttons.

Note these are shortcuts when Parlatype is focused. #18 is a different issue, it's about global shortcuts when Parlatype is not focused.

You had some other suggestions, please report them as separate issues if you need them.
My thoughts on them are:
* Configurable shortcuts: I don't think I would implement that. I'm not aware of a GNOME app that has configurable shortcuts and I don't want to make extra rounds.
* Custom timestamp formats: Do you have some special formats in mind? I'd rather not make it fully customizable but if there are other tools that are using other formats I could try to make it compatible.
* Move buttons around: At the moment I'd rather not change it.

**Comment by julianrichen** [comment]
> Configurable shortcuts: I don't think I would implement that. I'm not aware of a GNOME app that has configurable shortcuts and I don't want to make extra rounds.

I believe GNOME Builder & Pitivi are the only GNOME apps that have configurable shortcuts. Builder's aren't exposed in the app, instead used in the back-end to switch "Keyboard -> Emulation". Builder uses [libdazzle](https://github.com/GNOME/libdazzle/tree/master/src/shortcuts) and Pitivi [implemented themselves](https://github.com/GNOME/pitivi/blob/master/pitivi/shortcuts.py) in Python.

A lot of work imo. GNOME should have something like this upstream in GTK+.
