### ISSUE TITLE
Migrating Parlatype from Python 2 to 3

### ISSUE THREAD

**Issue by TheRadialActive** [gkarsay/parlatype#66]
Hello everyone,

I really like parlatype and hope to use it in the future. From 1. January 2020 python 2 reached end of life. Some of the dependencies like sphinxbase (https://github.com/cmusphinx/sphinxbase) seem to still rely on python 2. Is there a way to port parlatype to python 3 nontheless?

Thanks in advance!

**Comment by gkarsay** [comment]
I assume you are referring to the latest version, that is Parlatype 1.6.2.
* Sphinxbase is an optional dependency. You can disable it in Parlatype with `meson configure -Dasr=false`.
* If you want to build sphinxbase/pocketsphinx yourself, you can build them both using the configure option `--without-python` because Parlatype doesn't need its python interface.
* Probably you can build sphinxbase with python3 because Debian has a python3-sphinxbase package; maybe some patches are necessary for that.

Those are the options, if you build Parlatype yourself. The Flatpak version builds sphinxbase/pocketsphinx `--without-python`. If your distro is still using python2 for one of Parlatype's dependencies, please file a bug report for the distro package of that dependency.

If you are aware of other dependencies using python2, please let me know. I hope this helps and I'm closing this issue now. Please reopen if you think there is a still a problem.
