### ISSUE TITLE
Evaluate use of Mozilla Deep Speech for Autotranscripts

### ISSUE THREAD

**Issue by jdittrich** [gkarsay/parlatype#71]
In earlier versions, there was the option to use Pocketsphinx for transcription, but the results were not ideal. In case there is still interest in such a feature: 
[Mozilla’s Deep Speech](https://deepspeech.readthedocs.io/en/v0.6.1/USING.html) now has C/Python (and other language bindings) and smaller models and thus might be worth a try. 

Use cases would be:
* Getting a quick overview
* potentially adding automated timestamps
* rough transcript to be manually improved

**Comment by jdittrich** [comment]
I gave it a try in the python version with the stable 0.61.
- The model was pretty big (1GB – though afaic future models will be smaller to enable wider use of Mozilla DS)
- The recognition quality was good. Every 10th to 20th word was off, but not widely wrong either. 
- The python client was relatively easy to use, but for parlatype I guess one would use a C binding to the [GStreamer plugin](https://github.com/Elleo/gst-deepspeech)

**Comment by menelic** [comment]
Please try again - current release Deep Speech0.7..4 has far better accuracy rate at5.97% word error rate as compared to 7.5% word error rate with the 6.1 model you tried. The current model  far smaller models (180 MB and one with post training quantization at 41 MB). Find it here:

https://github.com/mozilla/DeepSpeech/releases/tag/v0.7.4

they release frequent updates: https://github.com/mozilla/DeepSpeech/releases  Given their focus on varieties of spoken language and dialects and the fact that they are building by far the largest open source speech recognition models for many languages it would be great if you could include them

**Comment by gkarsay** [comment]
I am aware of this issue and it is on my agenda. However, my first priority at the moment is to make Parlatype ready for GTK 4. This turned out to be more work than expected as the waveviewer widget needs massive architectural changes. I hope to solve this by the end of August this year.

I guess I will end up with something that allows to use arbitrary GStreamer elements, so every ASR solution that offers a GStreamer decoding element would work. This should be much more flexible than the current solution. The challenge is to make it not overly complicated to use.

Regarding Mozilla DeepSpeech, last time I had a look at it they had only an English model. I'm looking for an open source ASR engine that is packaged by distributions, has general-purpose language models of good quality (word error rate) for many languages. Unfortunately such a thing doesn't exist. Last time I checked it seemed that DeepSpeech will not be packaged by my distro (Debian) anytime soon (because of TensorFlow's build system, if I remember correctly) and Kaldi seemed very interesting to me. Anyway, as there is no perfect solution, I aim at supporting arbitrary GStreamer elements, including DeepSpeech.

**Comment by jdittrich** [comment]
> I guess I will end up with something that allows to use arbitrary GStreamer elements

Makes sense to me. 

> The challenge is to make it not overly complicated to use.

Feel free to poke me if you need usability evaluation/advice of possible implementations

> I'm looking for an open source ASR engine that is packaged by distributions, has general-purpose language models of good quality (word error rate) for many languages.  Unfortunately such a thing doesn't exist.

Yes… I think deep speech comes closest to a usable and useful solution for me, but still.
