### ISSUE TITLE
Setting the position of the play marker is difficult

### ISSUE THREAD

**Issue by jdittrich** [gkarsay/parlatype#79]
### Installation and version
parlatype 1.6.2 on Ubuntu 20.04 via normal repo
and
parlatype 2.1 on Ubuntu 20.04 via flatpack

### Issue
_Story:_ I want to (re) set the play marker so that the audio starts from a particular position. I do not want to set a region for playing,  but only a new start.
![Peek 2020-10-03 13-13](https://user-images.githubusercontent.com/3416487/94990185-67c45080-057a-11eb-8c0c-54795c964c31.gif)

_Problem:_ It is hard to set the play marker. I sometimes select super small areas that are repeated (only issuing a clacking sound or whatever is played in this fraction of a second) and it is hard to avoid doing so. I tried to click the audio visualization pressing Ctrl or clicking not in the waveform but below or above it, but nothing seemed to just move the marker.

**Comment by gkarsay** [comment]
Are you using the left mouse button? That's for selections. The right mouse button is for moving the cursor. Hope that helps, or is it something else?

**Comment by jdittrich** [comment]
Yes, I used the left mouse button. Did not know that I should move with the right one. Can be closed, then. 
However, consider to switch to left-mouse-button cursor moving which could be distinguished by considering anything with less then ~3px horizontal movement a move, rather than a select.

**Comment by gkarsay** [comment]
There is already a (closed, but not really resolved) issue #16 about selection mode. I thought of adding an option to switch left/right mouse button (left for positioning, right for selecting), Blender has a similar option to switch mouse buttons. It's mostly a matter of time.

I also thought of having different behaviour when the mouse is hovering over the waveform or the ruler. Audacity does this for example. However, the ruler is optional, so we can't depend on it. Or make the ruler mandatory.

> However, consider to switch to left-mouse-button cursor moving which could be distinguished by considering anything with less then ~3px horizontal movement a move, rather than a select.

I don't think that's practical: This would move the cursor on button click (because we want an immediate response). Then we would have to wait a bit to find out if there is a movement going on. If there is a movement, the cursor should be moved back to the previous position and a selection should be drawn. Besides, currently you can hold the right mouse button and move it.
