### ISSUE TITLE
New Debian/Ubuntu release? :)

### ISSUE THREAD

**Issue by boldandbusted** [gkarsay/parlatype#84]
Howdy. Just curious if there might be a new Debian/Ubuntu release in the near future? Thank you for Parlatype! :) Cheers.

**Comment by gkarsay** [comment]
The current stable version 2.1 is in Debian Testing (will be released as Debian 11 "Bullseye") and in Ubuntu 21.04 "Hirsute". I used to have a PPA for older Ubuntu releases, but I abandoned that because I have no time for it. I plan a new Parlatype release in the near future (next months) which will not make it into Debian 11 because it's already frozen.

**Comment by jubalh** [comment]
I think this is actually a downstream task.

**Comment by gkarsay** [comment]
Although I am downstream in this case I'd like to close this issue. Parlatype 3.0 is about to be released on Debian and will take some time until it makes its way into Ubuntu. Please note that I can't do any packaging for older Ubuntu versions anymore. If you want me to remind that there is a new version you can do that at the Debian bug tracker. Rest assured that I know about it already.
